### Section A: Data Structures & Control Structures

#### 1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
# Initial list
nums = [10, 20, 30, 40, 50]
print("Original list:", nums)

# append
nums.append(60)
print("After append:", nums)

# extend
nums.extend([70, 80])
print("After extend:", nums)

# insert
nums.insert(2, 25)
print("After insert at index 2:", nums)

# remove
nums.remove(40)
print("After removing 40:", nums)

# pop
nums.pop()  # removes last element
print("After pop:", nums)

# index
print("Index of 30:", nums.index(30))

# count
print("Count of 20:", nums.count(20))

# sort
nums.sort()
print("After sorting:", nums)

# reverse
nums.reverse()
print("After reversing:", nums)

# clear
nums.clear()
print("After clear:", nums)

Original list: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert at index 2: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After removing 40: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sorting: [10, 20, 25, 30, 50, 60, 70]
After reversing: [70, 60, 50, 30, 25, 20, 10]
After clear: []


#### 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [3]:
students = ("Ram", "Sita", "Raju")
print("Original tuple:", students)



# change second name                                     # tuples are immutable
students[1] = "Gita"

# convert back to tuple
students = tuple(students)
print("Updated tuple:", students)

Original tuple: ('Ram', 'Sita', 'Raju')


TypeError: 'tuple' object does not support item assignment

In [4]:
students = ("Ram", "Sita", "Raju")
print("Original tuple:", students)

# convert to list
temp = list(students)

# change second name                                          # tuples are immutable we can convert it into list---->change---->convert back
temp[1] = "Gita"                         
                                                                  
# convert back to tuple
students = tuple(temp)
print("Updated tuple:", students)

Original tuple: ('Ram', 'Sita', 'Raju')
Updated tuple: ('Ram', 'Gita', 'Raju')


#### 3.Create a set of integers with some duplicate values. Print the set and explain the output.


In [5]:
numbers = {1, 2, 2, 3, 4, 4, 5}
print("Set removes duplicates:", numbers)                      # sets are fundamentally designed to store only unique elements

Set removes duplicates: {1, 2, 3, 4, 5}


#### 4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [6]:
student = {
    "name": "Ravi",
    "age": 17,
    "city": "Delhi"
}

print("Original dictionary:", student)

# update age
student["age"] = 18

# add new key
student["email"] = "ravi@gmail.com"

print("Updated dictionary:", student)

Original dictionary: {'name': 'Ravi', 'age': 17, 'city': 'Delhi'}
Updated dictionary: {'name': 'Ravi', 'age': 18, 'city': 'Delhi', 'email': 'ravi@gmail.com'}


#### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [8]:
age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are NOT eligible to vote.")

Enter your age:  18


You are eligible to vote.


#### 6.Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [10]:
marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")

Enter marks:  100


Grade: A


#### 7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative. 

In [11]:
num = int(input("Enter a number: "))

if num > 0:
    if num % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

Enter a number:  10


The number is positive and even.


### Section B: Numpy

#### 8.Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [13]:
import numpy as np

scalar = np.array(5)
print("Scalar:\n", scalar)

Scalar:
 5


In [14]:
one_d = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", one_d)

1D Array:
 [1 2 3 4 5]


In [15]:
two_d = np.arange(10, 70, 10).reshape(2, 3)
print("2D Array (2x3):\n", two_d)

2D Array (2x3):
 [[10 20 30]
 [40 50 60]]


#### 9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [16]:
rand_arr = np.random.randint(0, 101, size=(4, 4))
print("Random 4x4 Array:\n", rand_arr)

Random 4x4 Array:
 [[34 40 79 81]
 [64 27 52 30]
 [67 63 77 98]
 [96 66 30 92]]


#### 10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [17]:
import numpy as np
import pandas as pd

# Create array
arr = np.random.randint(1, 100, size=(3, 3))

# Convert to DataFrame with column names
df = pd.DataFrame(arr, columns=["A", "B", "C"])

print("NumPy Array:\n", arr)
print("\nDataFrame:\n", df)

NumPy Array:
 [[16 98 95]
 [12 24 14]
 [86 13 62]]

DataFrame:
     A   B   C
0  16  98  95
1  12  24  14
2  86  13  62


### Section C: Exploring Pandas

#### 11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [19]:
import pandas as pd
import numpy as np


# 1. Create a DataFrame manually


data = {
    "Name": ["Amit", "Riya", "John", "Amit", "Sara", "Tom", "Neha", "Riya", "David", "John"],
    "Age": [25, 30, 22, 25, 28, 35, 27, 30, 40, 22],
    "City": ["Delhi", "Mumbai", "Kolkata", "Delhi", "Chennai", "Delhi", "Pune", "Mumbai", "Kolkata", "Kolkata"],
    "Salary": [50000, 60000, np.nan, 50000, 55000, 65000, 48000, 60000, np.nan, 70000]
}

df = pd.DataFrame(data)

print("\n Original DataFrame ")
print(df)


# 2. Use info() and describe()

print("\n DataFrame Info ")
print(df.info())

print("\n Describe ")
print(df.describe())


# 3. Select Name and City columns


print("\n Name & City Columns ")
print(df[["Name", "City"]])


# 4. Drop the City column

df = df.drop("City", axis=1)
print("\n After Dropping City Column ")
print(df)


# 5. Fill missing Salary with mean


mean_salary = df["Salary"].mean()
df["Salary"].fillna(mean_salary, inplace=True)

print("\n After Filling Missing Salary with Mean ")
print(df)


# 6. Remove duplicate rows


df = df.drop_duplicates()

print("\n Final DataFrame After Removing Duplicates ")
print(df)


 Original DataFrame 
    Name  Age     City   Salary
0   Amit   25    Delhi  50000.0
1   Riya   30   Mumbai  60000.0
2   John   22  Kolkata      NaN
3   Amit   25    Delhi  50000.0
4   Sara   28  Chennai  55000.0
5    Tom   35    Delhi  65000.0
6   Neha   27     Pune  48000.0
7   Riya   30   Mumbai  60000.0
8  David   40  Kolkata      NaN
9   John   22  Kolkata  70000.0

 DataFrame Info 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

 Describe 
             Age        Salary
count  10.000000      8.000000
mean   28.400000  57250.000000
std     5.680376   7869.470848
min    22.000000  48000.000000
25%    25.000000  50000.000000
50%    27.50000

C:\Users\moulika\AppData\Local\Temp\ipykernel_10632\3287226808.py:48: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(mean_salary, inplace=True)
